version: "3.7"
services:
  n8n:
    image: osiris-n8n
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      OSIRIS_API: http://127.0.0.1:8080
      EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: "true"
      EXECUTIONS_DATA_SAVE_ON_ERROR: "all"
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: "all"
    container_name: osiris-n8n
    ports: ["5678:5678"]
